.PHONY: clean All

All:
	@echo "----------Building project:[ AudioMixer - Release ]----------"
	@cd "AudioMixer" && "$(MAKE)" -f  "AudioMixer.mk" && "$(MAKE)" -f  "AudioMixer.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ AudioMixer - Release ]----------"
	@cd "AudioMixer" && "$(MAKE)" -f  "AudioMixer.mk" clean
