.PHONY: clean All

All:
	@echo "----------Building project:[ AudioMixer - Debug ]----------"
	@cd "AudioMixer" && "$(MAKE)" -f  "AudioMixer.mk"
clean:
	@echo "----------Cleaning project:[ AudioMixer - Debug ]----------"
	@cd "AudioMixer" && "$(MAKE)" -f  "AudioMixer.mk" clean
